# Generated by Django 4.2.15 on 2024-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[('Est', 'Est'), ('Ouest', 'Ouest'), ('Centre', 'Centre')], default='EST', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='region',
            field=models.CharField(blank=True, choices=[('Est', 'Est'), ('Ouest', 'Ouest'), ('Centre', 'Centre')], default='EST', max_length=6, null=True),
        ),
    ]
