# Generated by Django 4.2.15 on 2024-11-23 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Session.ville'),
            preserve_default=False,
        ),
    ]
