# Generated by Django 4.2.15 on 2024-11-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_customuser_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Session.ville'),
        ),
    ]
