# Generated by Django 4.2.15 on 2024-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_userurlhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
