# Generated by Django 4.2.15 on 2024-08-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dist_BonLivraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facture', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('date_facturation', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('fc_file', models.FileField(blank=True, null=True, upload_to='Factures')),
                ('bl_file', models.FileField(blank=True, null=True, upload_to='BonLivraison')),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dist_BonLivraisonLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prixtotal', models.FloatField()),
                ('prixunitaire', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dist_Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('Reception', 'Receptions Et Enregistrement'), ('Traitement', 'Validation Et Traitement'), ('Preparation', 'Preparation'), ('En cours', "En Cours D'expedition"), ('Complete', 'Complete'), ('Annule', 'Annulé')], default='Reception', max_length=20)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dist_CommandeLines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prixtotal', models.FloatField()),
                ('prixunitaire', models.FloatField()),
                ('complete', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandesLines', to='Commande.dist_commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produit')),
            ],
        ),
    ]
