# Generated by Django 4.2.15 on 2024-08-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produits', '0003_alter_produit_reference'),
        ('Distributeur', '0007_payeur_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dist_Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('Reception', 'Receptions Et Enregistrement'), ('Traitement', 'Validation Et Traitement'), ('Preparation', 'Preparation'), ('En cours', "En Cours D'expedition"), ('Complete', 'Complete'), ('Annule', 'Annulé')], default='Reception', max_length=20)),
                ('total', models.FloatField(default=0)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distributeur.distributeur')),
            ],
        ),
        migrations.CreateModel(
            name='Dist_CommandeLines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prixtotal', models.FloatField()),
                ('prixunitaire', models.FloatField()),
                ('complete', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandesLines', to='Commande.dist_commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produit')),
            ],
        ),
    ]
