# Generated by Django 4.2.15 on 2024-12-05 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commande', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dist_commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dist_bonlivraisonline',
            name='bl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BonLivraison', to='Commande.dist_bonlivraison'),
        ),
        migrations.AddField(
            model_name='dist_bonlivraisonline',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produit'),
        ),
        migrations.AddField(
            model_name='dist_bonlivraison',
            name='commandes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BLCMD', to='Commande.dist_commande'),
        ),
    ]
