# Generated by Django 4.2.15 on 2024-08-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_alter_produit_reference'),
        ('Commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dist_BonLivraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facture', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('date_facturation', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('fc_file', models.FileField(blank=True, null=True, upload_to='Factures')),
                ('bl_file', models.FileField(blank=True, null=True, upload_to='BonLivraison')),
                ('commandes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BLCMD', to='Commande.dist_commande')),
            ],
        ),
        migrations.CreateModel(
            name='Dist_BonLivraisonLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prixtotal', models.FloatField()),
                ('prixunitaire', models.FloatField()),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BonLivraison', to='Commande.dist_bonlivraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produit')),
            ],
        ),
    ]
