# Generated by Django 4.2.15 on 2024-08-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_dist_bonlivraison_dist_bonlivraisonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dist_bonlivraison',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
