# Generated by Django 4.2.15 on 2024-12-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0003_dist_bonlivraison_payeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dist_bonlivraison',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
