# Generated by Django 4.2.15 on 2024-12-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0004_dist_bonlivraison_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dist_commande',
            name='etat',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Reception', 'Receptions Et Enregistrement'), ('Traitement', 'Validation Et Traitement'), ('Preparation', 'Preparation'), ('En cours', "En Cours D'expedition"), ('Complete', 'Complete'), ('Annule', 'Annulé')], default='Reception', max_length=20),
        ),
    ]
