# Generated by Django 4.2.15 on 2024-11-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Distributeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('nbrplace', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('tarif', models.FloatField()),
                ('datedebut', models.DateField()),
                ('dateajout', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problematique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Reclamation', 'Reclamation'), ('Intervention', 'Intervention')], default='Reclamation', max_length=30)),
                ('intitule', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('Reception', 'Reception'), ('En cours', 'En cours'), ('Validation', 'Validation'), ('Confirmation', 'Confirmation')], default='Reception', max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distributeur.distributeur')),
            ],
        ),
        migrations.CreateModel(
            name='FormationSingup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nbrelem', models.IntegerField(default=0)),
                ('prixtotal', models.FloatField(default=0)),
                ('dateajout', models.DateField(auto_now_add=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distributeur.distributeur')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('dateajout', models.DateField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipeline', to='Formation.formationsingup')),
            ],
        ),
    ]
