# Generated by Django 4.2.15 on 2024-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problematique',
            name='erreur',
        ),
        migrations.AlterField(
            model_name='problematique',
            name='date_ajout',
            field=models.DateField(auto_now_add=True),
        ),
    ]
