# Generated by Django 4.2.15 on 2024-12-12 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='centre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='est',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='lieu',
            field=models.CharField(default=1, max_length=260),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='ouest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagesFormation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='Formation')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.formation')),
            ],
        ),
    ]
