# Generated by Django 4.2.15 on 2024-12-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_formation_centre_formation_est_formation_lieu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesProblematique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='Problematique')),
                ('problematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.problematique')),
            ],
        ),
    ]
