# Generated by Django 4.2.15 on 2024-11-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_remove_problematique_erreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problematique',
            name='intitule',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='problematique',
            name='message',
            field=models.TextField(),
        ),
    ]
