# Generated by Django 4.2.15 on 2024-11-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0003_alter_problematique_intitule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationsingup',
            name='nbrelem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formationsingup',
            name='prixtotal',
            field=models.FloatField(default=0),
        ),
    ]
