# Generated by Django 4.2.15 on 2024-08-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Distributeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_init', models.FloatField(default=0)),
                ('montant', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('Cheque', 'Cheque'), ('Virement', 'Virement'), ('Espece', 'Espece')], default='Cheque', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('validation', models.BooleanField(default=False)),
                ('validation_depot', models.BooleanField(default=False)),
                ('date_depot', models.DateField(blank=True, null=True)),
                ('date_cheque', models.DateField(blank=True, null=True)),
                ('substitution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('montant', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('Cheque', 'Cheque'), ('Virement', 'Virement'), ('Espece', 'Espece')], default='Cheque', max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('validation', models.BooleanField(default=False)),
                ('validation_depot', models.BooleanField(default=False)),
                ('date_depot', models.DateField(blank=True, null=True)),
                ('date_cheque', models.DateField(blank=True, null=True)),
                ('substitution', models.BooleanField(default=False)),
                ('listefacturesub', models.CharField(blank=True, max_length=255, null=True)),
                ('banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Encaissement.banque')),
                ('payeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distributeur.payeur')),
            ],
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('montant', models.FloatField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('fc_file', models.FileField(blank=True, null=True, upload_to='')),
                ('payeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distributeur.payeur')),
            ],
        ),
        migrations.CreateModel(
            name='EncaissementFacture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Encaissement', 'Encaissement'), ('Account', 'Account')], default='Encaissement', max_length=20)),
                ('montant', models.FloatField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Encaissement.account')),
                ('encaissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Encaissement.encaissement')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facture_encaissement', to='Encaissement.factures')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Encaissement.banque'),
        ),
        migrations.AddField(
            model_name='account',
            name='encaissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Encaissement.encaissement'),
        ),
        migrations.AddField(
            model_name='account',
            name='payeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distributeur.payeur'),
        ),
        migrations.AddField(
            model_name='account',
            name='payeursubstite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payeursubstite', to='Distributeur.payeur'),
        ),
    ]
