# Generated by Django 4.2.15 on 2024-08-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encaissement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
