# Generated by Django 4.2.15 on 2024-12-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_initial'),
        ('Encaissement', '0002_alter_factures_payeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='payeur',
        ),
        migrations.AddField(
            model_name='factures',
            name='bl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Commande.dist_bonlivraison'),
            preserve_default=False,
        ),
    ]
