# Generated by Django 4.2.15 on 2024-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encaissement', '0002_alter_factures_date_echeance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
