# Generated by Django 4.2.15 on 2024-08-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encaissement', '0002_alter_encaissement_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='montant_ttc',
            field=models.FloatField(default=0),
        ),
    ]
