# Generated by Django 4.2.15 on 2024-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encaissement', '0003_alter_account_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
