# Generated by Django 4.2.15 on 2024-12-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encaissement', '0005_factures_payeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='payeur',
        ),
    ]
