# Generated by Django 4.2.15 on 2024-08-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeur',
            name='objectif_a',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='objectif_m',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='ristourn_a',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='ristourn_na',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
