# Generated by Django 4.2.15 on 2024-08-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0002_alter_distributeur_objectif_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payeur',
            old_name='numero',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='distributeur',
            name='numero',
        ),
    ]
