# Generated by Django 4.2.15 on 2024-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeur',
            name='art_file',
            field=models.FileField(blank=True, null=True, upload_to='PayeurData'),
        ),
        migrations.AddField(
            model_name='payeur',
            name='nif_file',
            field=models.FileField(blank=True, null=True, upload_to='PayeurData'),
        ),
        migrations.AddField(
            model_name='payeur',
            name='nis_file',
            field=models.FileField(blank=True, null=True, upload_to='PayeurData'),
        ),
        migrations.AddField(
            model_name='payeur',
            name='rc_file',
            field=models.FileField(blank=True, null=True, upload_to='PayeurData'),
        ),
    ]
