# Generated by Django 4.2.15 on 2024-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0003_rename_numero_payeur_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeur',
            name='objectif_a',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='objectif_m',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='ristourn_a',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='ristourn_na',
            field=models.FloatField(default=0),
        ),
    ]
