# Generated by Django 4.2.15 on 2024-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0004_alter_distributeur_objectif_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeur',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
