# Generated by Django 4.2.15 on 2024-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0005_payeur_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
