# Generated by Django 4.2.15 on 2024-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributeur', '0006_payeur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeur',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
