# Generated by Django 4.2.15 on 2024-08-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Unité', 'Unité'), ('Sac', 'Sac')], default='Unité', max_length=12)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Produit/')),
                ('prix_publique', models.FloatField(default=0)),
                ('prix_gros', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.couleur')),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.mesure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.typeproduit')),
            ],
        ),
    ]
