# Generated by Django 4.2.15 on 2024-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_mesure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
